update branch commit

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -39,13 +39,20 @@ jobs:
 
       - name: Run tests
         run: |
-          set -x
           echo "Testing connection..."
           for i in {1..10}; do
             curl -s 127.0.0.1:8000 > /dev/null && break
             echo "Waiting for server..."
             sleep 1
           done
+
+          if ! curl -s 127.0.0.1:8000 > /dev/null; then
+            echo "Error: Server did not respond after 10 attempts."
+            exit 1
+          fi
+
+          echo "Okay: Connection Success"
+          
           ./example_requests/default_request.sh
 
           cat output.json
